## Aula 15/12/2025

### Biblioteca Pandas 🐼

Utilização: Praticamente todas as vezes que precisarmos manipular e/ou tratar dados de diversos tipos de arquivos, exemplo: .xlsx e .csv

**Características**
- Fácil de utilizar
- Documentação rica
- Comunidade muito ativa
- Objetos centrais do pandas são as Series e os DataFrames

**Vantagens**
- Integração com Matplotlib
- Integração com Numpy
- Integração com Seaborn
- Integração com Scikit-learn

<a href="https://pandas.pydata.org/docs/">Biblioteca Pandas</a>

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

d = {'a': 1, 'b': 2, 'c': 3}
ser = pd.Series(data=d, index=['a', 'b', 'c'])

In [6]:
print(ser)
print(type(ser))

a    1
b    2
c    3
dtype: int64
<class 'pandas.core.series.Series'>

In [8]:
ser.describe()

count    3.0
mean     2.0
std      1.0
min      1.0
25%      1.5
50%      2.0
75%      2.5
max      3.0
dtype: float64

In [10]:
# Acessar valores pelos 
print(ser['a'])
print(ser['b'])
print(ser['c'])

1
2
3

In [11]:
np.mean([1, 2, 3, 3, 3, 4, 5])

3.0

In [12]:
np.var([1, 2, 3, 3, 3, 4, 5])

1.4285714285714286

In [13]:
np.std([1, 2, 3, 3, 3, 4, 5])

1.1952286093343936

### DataFrame

In [14]:
import pandas as pd

d = {'col1': [1, 2], 'col2': [3, 4]}
df = pd.DataFrame(data=d)
df

   col1  col2
0     1     3
1     2     4

In [23]:
import pandas as pd

d = {'nome': ['João', 'Ana'], 'vendas Dez 25': [3, 4]}
df = pd.DataFrame(data=d)
df

   nome  vendas Dez 25
0  João              3
1   Ana              4

In [24]:
df.index

RangeIndex(start=0, stop=2, step=1)

In [25]:
len(df)

2

In [26]:
df.iloc[0]

nome             João
vendas Dez 25       3
Name: 0, dtype: object

In [27]:
df.iloc[1]

nome             Ana
vendas Dez 25      4
Name: 1, dtype: object

In [28]:
df['nome']

0    João
1     Ana
Name: nome, dtype: object

In [29]:
df['vendas Dez 25']

0    3
1    4
Name: vendas Dez 25, dtype: int64

In [30]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 2 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   nome           2 non-null      object
 1   vendas Dez 25  2 non-null      int64
dtypes: int64(1), object(1)
memory usage: 164.0+ bytes